### PR TITLE
Update favicon.ico

### PR DESCRIPTION
**Pull request by Mark-a-obrien**
- Added a new faveicon in the style of the project
image

- Cookies for the site have to be deleted for it to update

### CODE REVIEW

**Comment by LeviGreen** [comment]
Great idea! Instead of using a binary file (.ico), see if you can implement this using an "SVG"; that way, we can view the image in HTML-esque code that can be iterated on over time.

**Comment by Mark-a-obrien** [comment]
Hi @LeviGreen,
I've converted it to svg.

**Comment by LeviGreen** [comment]
Please convert this to a regular PR and I will approve.

**Review by LeviGreen — APPROVED** [review]
LGTM

**Comment by LeviGreen** [comment]
@Mark-a-obrien Are you able to recover this branch so that I can merge it?

**Comment by Mark-a-obrien** [comment]
> @Mark-a-obrien Are you able to recover this branch so that I can merge it?

Oh sorry about that. I restored it. Still getting used to GitHub :)

**Comment by LeviGreen** [comment]
No worries! Your change is [now live](https://levigreen.github.io/master-mind/)

**Pull request merged**
