### PR TITLE
Update winModal.js : confetti colors matches the answer colors

### PR DESCRIPTION
**Pull request by Mark-a-obrien**
- The confetti colors now matches the answer colors

- Screenshot of the confetti colors and answer colors side by side
image

### CODE REVIEW

**Comment by LeviGreen** [comment]
Hi @Mark-a-obrien, just wondering how you found my project 😄

**Comment by LeviGreen** [comment]
Thank you for your interest in contributing! I developed this game to flex my React skills and am delighted with how it has turned out. Initially, I made this repository public and created specific "Issues" to help a colleague learn coding. Unexpectedly, your solution aligns perfectly with how I hope my colleague will approach these challenges. Therefore, I've decided to close this pull request to give my colleague the opportunity to tackle it independently.

If you have any suggestions or improvements for the application, please continue to submit pull requests. Your contributions are welcome and appreciated! 🙂

**Comment by Mark-a-obrien** [comment]
> Hi @Mark-a-obrien, just wondering how you found my project 😄

Hi @LeviGreen, 
I was just looking at projects with JavaScript and came across yours 😄. Glad I did it was a fun little issue.

**Comment by Mark-a-obrien** [comment]
> Thank you for your interest in contributing! I developed this game to flex my React skills and am delighted with how it has turned out. Initially, I made this repository public and created specific "Issues" to help a colleague learn coding. Unexpectedly, your solution aligns perfectly with how I hope my colleague will approach these challenges. Therefore, I've decided to close this pull request to give my colleague the opportunity to tackle it independently.
> 
> If you have any suggestions or improvements for the application, please continue to submit pull requests. Your contributions are welcome and appreciated! 🙂

I'm glad the solutions aligns with what you expected from your colleague. I'm still quite knew to react and this is my first commit to a project that isn't my own. Thanks for the opportunity. 

I will definitely submit another pull request if/when I any suggestions or improvements.
Thank again.

**Pull request closed without merging**
